# Generated by Django 2.1 on 2019-04-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='商品分类名称')),
                ('image', models.ImageField(blank=True, upload_to='category/')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('abstract', models.CharField(max_length=200, verbose_name='商品简介')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='商品价格')),
                ('unit', models.CharField(max_length=20, verbose_name='商品的售卖单位')),
                ('stock', models.IntegerField(default=0, verbose_name='商品库存')),
                ('desc', models.TextField(null=True, verbose_name='详细介绍')),
                ('pic', models.ImageField(upload_to='goods/%Y/%m/%d', verbose_name='商品图片')),
                ('popular', models.IntegerField(default=0, verbose_name='人气指数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='df_goods.CategoryModel', verbose_name='商品的分类')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 'goods',
            },
        ),
    ]
