# Generated by Django 2.2 on 2019-05-16 08:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='abstract',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=200, verbose_name='商品简介'),
        ),
    ]
