# Generated by Django 2.2 on 2019-05-16 08:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20190516_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='abstract',
            field=models.CharField(max_length=200, verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='详细介绍'),
        ),
    ]
